[package]
name = "git-branch-status"
version = "0.1.0"
authors = ["Akiomi Kamakura <akiomik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.18"
ansi_term = "0.12"
clap = "4.5.1"
