name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "test-release-*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu	
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # - os: macos-latest
          #   target: aarch64-apple-darwin
          # - os: macos-latest
          #   target: x86_64-apple-darwin

    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo apt-get install libssl-dev pkg-config build-essential gcc-8-aarch64-linux-gnu g++-8-aarch64-linux-gnu
      # - run: sudo apt-get install libssl-dev pkg-config
      # - run: sudo apt-get install g++-arm-linux-gnueabihf
      #   if: matrix.os == 'ubuntu-latest'
      # - uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     target: ${{ matrix.target }}
      #     override: true
      # - uses: actions-rs/cargo@v1
      #   with:
      #     use-cross: true
      #     command: build
      #     args: --release --target ${{ matrix.target }} --all-features
      - run: rustup target add ${{ matrix.target }}
      - run: cargo build --release --target ${{ matrix.target }}
        env:
          OPENSSL_LIB_DIR: /usr/lib/x86_64-linux-gnu
          OPENSSL_INCLUDE_DIR: /usr/include/openssl
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            README.md
            LICENSE
            target/**/release/git-branch-status
